name: cicd

on: push

jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2


    - name: Setup nodejs
      uses: action/setup-node@v2
      with:
        node-version: 16
    - name: Download dependecies
      run: nmp install

    - name: Run tests
      run: npm run tests
